### ISSUE TITLE
how to get ContentDocument Id for the file you want to present?

### ISSUE THREAD

**Issue by annyhe** [zaynelt/presenter-magic#2]
Hello @zaynelt ,

I followed all the directions in README.md to populate the scratch org.
Also added a powerpoint file on the Assembler tab.
How to get ContentDocument Id for the file you want to present? Is it possible from the UI?
Is ContentDocument Id part of the Public url?

<img width="992" alt="screen shot 2018-09-19 at 10 52 49 am" src="https://user-images.githubusercontent.com/17040750/45771593-5eb5f000-bbfa-11e8-9245-7406a898b7c9.png">

**Comment by zaynelt** [comment]
Hey Anne,

The ID for the ContentDocument will be visible in the URL when you go to the 'View File Details' view as described here: https://help.salesforce.com/articleView?id=collab_files_previewing.htm&type=5
