### ISSUE TITLE
missing "keynoteSlides" attribute 

### ISSUE THREAD

**Issue by annyhe** [zaynelt/presenter-magic#3]
Hello @zaynelt,
 
From README.md
> In order to use the Launchpad, you'll need to update the 'keynoteSlides' attribute in the slidePresenter component markup to match the ContentDocument Id for the file you want to present.

I added a `keynoteSlides` attribute in `slidePresenter.cmp`, so it looks like
`    <aura:attribute name="keynoteFile" type="String" 
        keynoteSlides="0693D00000074TAQAY" default="0693D00000074TAQAY"/>`

The associated powerpoint still does not show up.
<img width="780" alt="screen shot 2018-09-19 at 2 10 12 pm" src="https://user-images.githubusercontent.com/17040750/45781758-cded0d80-bc15-11e8-8841-88179d27837c.png">

Do we need to change any other attributes?

**Comment by zaynelt** [comment]
Hey Anny, you should *only* update line 2 of the 'slidePresenter.cmp' file. You just need to change the 'default' value to the Id you've grabbed (beginning w/ '069').
